In [ ]:
import torch
import torch.nn as nn

class Model(nn.Module):

  def __init__(self,num_features):
     super().__init__()
     self.linear= nn.Linear(num_features,1)
     self.sigmoid= nn.Sigmoid()

  def forward(self,features):
    out= self.linear(features)
    out= self.sigmoid(out)
    return out

In [ ]:
# create datasets
features= torch.rand(10,5)

# create model
model= Model(features.shape[1])

# call model for forward pass
model(features)

tensor([[0.5201],
        [0.5321],
        [0.5089],
        [0.5434],
        [0.5688],
        [0.5671],
        [0.5490],
        [0.5419],
        [0.5386],
        [0.5844]], grad_fn=<SigmoidBackward0>)

In [ ]:
model.linear.weight

Parameter containing:
tensor([[ 0.1239,  0.4129,  0.1894,  0.2083, -0.1472]], requires_grad=True)

In [ ]:
model.linear.bias

Parameter containing:
tensor([-0.2544], requires_grad=True)

In [ ]:
!pip install torchinfo

In [ ]:
from torchinfo import summary
summary(model,input_size=(10,5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 1]                   6
├─Sigmoid: 1-2                           [10, 1]                   --
Total params: 6
Trainable params: 6
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

In [ ]:
import torch
import torch.nn as nn

class Model(nn.Module):

  def __init__(self,num_features):
     super().__init__()
     self.linear1= nn.Linear(num_features,3)
     self.relu= nn.ReLU()
     self.linear2= nn.Linear(3,1)
     self.sigmoid= nn.Sigmoid()

  def forward(self,features):
    out= self.linear1(features)
    out= self.relu(out)
    out= self.linear2(out)
    out= self.sigmoid(out)
    return out

In [ ]:
# create datasets
features= torch.rand(10,5)

# create model
model= Model(features.shape[1])

# call model for forward pass
model(features)

tensor([[0.4507],
        [0.4462],
        [0.4693],
        [0.4469],
        [0.3912],
        [0.4301],
        [0.4420],
        [0.4397],
        [0.4573],
        [0.4027]], grad_fn=<SigmoidBackward0>)

In [ ]:
model.linear2.bias

Parameter containing:
tensor([-0.2830], requires_grad=True)

In [ ]:
model.linear1.weight

Parameter containing:
tensor([[ 0.4450, -0.2190, -0.1706,  0.4020,  0.1236],
        [-0.0339, -0.2379, -0.3574,  0.2726, -0.2105],
        [ 0.2900,  0.2952, -0.4417,  0.1487,  0.0887]], requires_grad=True)

In [ ]:
from torchinfo import summary
summary(model,input_size=(10,5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 3]                   18
├─ReLU: 1-2                              [10, 3]                   --
├─Linear: 1-3                            [10, 1]                   4
├─Sigmoid: 1-4                           [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

In [ ]:
# create model class
import torch
import torch.nn as nn

class Model(nn.Module):

  def __init__(self, num_features):

    super().__init__()
    self.network = nn.Sequential(
        nn.Linear(num_features, 3),
        nn.ReLU(),
        nn.Linear(3, 1),
        nn.Sigmoid()
    )

  def forward(self, features):

    out = self.network(features)

    return out

In [ ]:
# create datasets
features= torch.rand(10,5)

# create model
model= Model(features.shape[1])

# call model for forward pass
model(features)

tensor([[0.5686],
        [0.4899],
        [0.5595],
        [0.5802],
        [0.5362],
        [0.5999],
        [0.5343],
        [0.5639],
        [0.5592],
        [0.5364]], grad_fn=<SigmoidBackward0>)

AttributeError: 'Model' object has no attribute 'linear'