In [ ]:
# import torch and check version
import torch
print(torch.__version__)

2.6.0+cu124


In [ ]:
# Check which is using CPU OR TPU and its name
if torch.cuda.is_available():
    print("GPU is available")
    print(f"Using GPU:{torch.cuda.get_device_name(0)}")
else:
  print("GPU not avaliable .Using CPU")

GPU is available
Using GPU:Tesla T4


Creating a Tensor

In [ ]:
# using empty to create a empty tensor
# they allocate a memory for you, they did  not assign a value for that space
# the value that is already existing in the space he as it shows you it first
# yr phele se hi value pari huyi thi wo dekha deta hai
a=torch.empty(2,3)


In [ ]:
# check type
a.type

<function Tensor.type>

In [ ]:
# using zeros
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [ ]:
# using ones
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [ ]:
# using rand [0-1] randomly
torch.rand(2,3)


tensor([[0.1693, 0.3362, 0.0628],
        [0.5789, 0.9825, 0.7923]])

In [ ]:
# using manual_seed(100)
#if you want to print same value using rand then used "Seed" for YouTubeVideo
torch.manual_seed(2)
torch.rand(2,3)

tensor([[0.6147, 0.3810, 0.6371],
        [0.4745, 0.7136, 0.6190]])

In [ ]:
torch.manual_seed(2)
torch.rand(2,3)

tensor([[0.6147, 0.3810, 0.6371],
        [0.4745, 0.7136, 0.6190]])

In [ ]:
# custom tensor creating
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
# arange : jump on number, start from 0, end with 10, jump on 2
print("using arange ->", torch.arange(0,10,2))


using arange -> tensor([0, 2, 4, 6, 8])


In [ ]:
# linspace : they create a number which is equally distributed witin the number split
torch.linspace(0,10,5)

tensor([ 0.0000,  2.5000,  5.0000,  7.5000, 10.0000])

In [ ]:
# eye :identity matrix,they create a matrix which has diganolly 1
torch.eye(3)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [ ]:
# full :print all items which is equall
torch.full((2,3), 10)

tensor([[10, 10, 10],
        [10, 10, 10]])

Tensor shapes

In [ ]:
x= torch.tensor([[1,2,3],[4,5,6]])


In [ ]:
x.shape

torch.Size([2, 3])

copy the shape of another matrix
with the help of "LIke"

In [ ]:
# with empty
torch.empty_like(x)

tensor([[       64,       192, 145687032],
        [      134,         0,         0]])

In [ ]:
# with zeros
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [ ]:
# with ones
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [ ]:
# with random values, you have to specity datatype bcz  rand print only value from "0 to 1" only float
torch.rand_like(x.float())

tensor([[0.4425, 0.0958, 0.6142],
        [0.0573, 0.5657, 0.5332]])

Tensor Data Types

In [ ]:
x.dtype

torch.int64

In [ ]:
# assign the data types with same time specify its datatypes
torch.tensor(data=[1,2,3,4,5], dtype=torch.int32 )

tensor([1, 2, 3, 4, 5], dtype=torch.int32)

In [ ]:
torch.tensor([1,2,3,4,5], dtype=torch.int32 )

tensor([1, 2, 3, 4, 5], dtype=torch.int32)

In [ ]:
torch.tensor([1,2,3],dtype=torch.float64)

tensor([1., 2., 3.], dtype=torch.float64)

To convert its  datatypes of matrix

In [ ]:
x.to(torch.float32)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

Mathematical OPerations


1.Scaler Operations

In [ ]:
x=torch.tensor([[2,2,2,2],[2,2,2,2]])
x

tensor([[2, 2, 2, 2],
        [2, 2, 2, 2]])

In [ ]:
# addition
x+2

tensor([[4, 4, 4, 4],
        [4, 4, 4, 4]])

In [ ]:
# Subtraction
x-2

tensor([[0, 0, 0, 0],
        [0, 0, 0, 0]])

In [ ]:
# division
x/2

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
# Muliplication
x*2

tensor([[4, 4, 4, 4],
        [4, 4, 4, 4]])

In [ ]:
# int division
(x *100)//2

tensor([[100, 100, 100, 100],
        [100, 100, 100, 100]])

In [ ]:
# mod
((x*100)//2)%2

tensor([[0, 0, 0, 0],
        [0, 0, 0, 0]])

In [ ]:
x//2

tensor([[1, 1, 1, 1],
        [1, 1, 1, 1]])

In [ ]:
x/2

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]])

Element wiae Operation

In [ ]:
a=torch.rand(2,3)
b=torch.rand(2,3)
print("a:",a)
print("b:",b)

a: tensor([[0.3984, 0.7909, 0.5555],
        [0.9628, 0.7536, 0.0727]])
b: tensor([[0.6463, 0.9804, 0.9441],
        [0.4921, 0.6659, 0.0310]])


In [ ]:
# add
a+b

tensor([[1.0447, 1.7713, 1.4997],
        [1.4549, 1.4195, 0.1036]])

In [ ]:
a-b

tensor([[-0.2479, -0.1896, -0.3886],
        [ 0.4706,  0.0877,  0.0417]])

In [ ]:
# multiply
a*b

tensor([[0.2575, 0.7754, 0.5245],
        [0.4738, 0.5018, 0.0023]])

In [ ]:
# division
a/b

tensor([[0.6164, 0.8066, 0.5884],
        [1.9563, 1.1317, 2.3462]])

In [ ]:
# mod
a%b

tensor([[0.3984, 0.7909, 0.5555],
        [0.4706, 0.0877, 0.0107]])

In [ ]:
c= torch.tensor([1,-2,3,-4])

In [ ]:
# abs
torch.abs(c)

tensor([1, 2, 3, 4])

In [ ]:
# negative
torch.neg(c)

tensor([-1,  2, -3,  4])

In [ ]:
d=torch.tensor([1,1.9,2.5,9.9])

In [ ]:
# Round
torch.round(d)

tensor([ 1.,  2.,  2., 10.])

In [ ]:
# ceil
torch.ceil(d)

tensor([ 1.,  2.,  3., 10.])

In [ ]:
# floor
torch.floor(d)

tensor([1., 1., 2., 9.])

In [ ]:
# clamp :it have to used in certain range, TO change its max and min values, within the bounday, just the reduce and increse its box plot
torch.clamp(d,min=1.5,max=2.5)

tensor([1.5000, 1.9000, 2.5000, 2.5000])

3. Reduction operation

In [ ]:
e= torch.randint(size=(2,3),low=0,high=10,dtype=torch.float32)
e

tensor([[2., 0., 0.],
        [8., 4., 6.]])

In [ ]:
# sum
torch.sum(e)

tensor(20.)

In [ ]:
# sum by dimensions or axis
torch.sum(e,axis=0)


tensor([10.,  4.,  6.])

In [ ]:
torch.sum(e,axis=1)

tensor([ 2., 18.])

In [ ]:
# mean
torch.mean(e)

tensor(3.3333)

In [ ]:
torch.mean(e,axis=0)

tensor([5., 2., 3.])

In [ ]:
# min and max
torch.min(e)

tensor(0.)

In [ ]:
torch.max(e)

tensor(8.)

In [ ]:
# product
torch.prod(e)

tensor(0.)

In [ ]:
# standard Deviation
torch.std(e)

tensor(3.2660)

In [ ]:
# Variance
torch.var(e)

tensor(10.6667)

In [ ]:
# argmax : it is used to find the position of max values
torch.argmax(e)

tensor(3)

In [ ]:
# argmin
torch.argmin(e)

tensor(1)

4. Matrix Operation

In [ ]:
f= torch.randint(size=(2,3), low=0, high=10)
g= torch.randint(size=(3,2),low=0,high=10)
print("f:",f)
print("g:",g)

f: tensor([[0, 1, 3],
        [3, 1, 7]])
g: tensor([[1, 8],
        [0, 0],
        [8, 7]])


In [ ]:
# Matrix multiplication
torch.matmul(f,g)

tensor([[24, 21],
        [59, 73]])

In [ ]:
ff= torch.randint(size=(2,3), low=0, high=10)
gg= torch.randint(size=(2,3),low=0,high=10)
print("ff:",ff)
print("gg:",gg)
 # matrix multiplication with Transpose of ff

torch.matmul(ff.T,gg)

ff: tensor([[3, 3, 5],
        [2, 3, 0]])
gg: tensor([[9, 3, 5],
        [3, 2, 7]])


tensor([[33, 13, 29],
        [36, 15, 36],
        [45, 15, 25]])

In [ ]:
vector1=torch.tensor([1,2,3])
vector2=torch.tensor([4,5,6])

In [ ]:
# Dot Product
torch.dot(vector1,vector2)

tensor(32)

In [ ]:
h= torch.randint(size=(3,3), low=0, high=10,dtype=torch.float32)
# Determinant
torch.det(h)

tensor(-82.)

In [ ]:
# inverse
torch.inverse(h)

tensor([[-0.3171,  0.1220,  0.0732],
        [ 0.4146,  0.1098, -0.1341],
        [ 0.2439, -0.1707,  0.0976]])

5. Comparison Operation

In [ ]:
i= torch.randint(size=(2,3), low=0,high=10)
j= torch.randint(size=(2,3), low=0,high=10)
print(i)
print(j)

tensor([[7, 2, 3],
        [6, 5, 7]])
tensor([[0, 0, 1],
        [4, 1, 9]])


In [ ]:
# greater than
i>j


tensor([[ True,  True,  True],
        [ True,  True, False]])

In [ ]:
# less than
i <j

tensor([[False, False, False],
        [False, False,  True]])

In [ ]:
# not equal to
i!=j


tensor([[True, True, True],
        [True, True, True]])

In [ ]:
# greater than equal to
i >= j

tensor([[ True,  True,  True],
        [ True,  True, False]])

In [ ]:
# less than equal to
i <=j

tensor([[False, False, False],
        [False, False,  True]])

6. Sepcial Functions

In [ ]:
k= torch.randint(size=(2,3), low=0, high=10,dtype= torch.float32)
k

tensor([[1., 7., 3.],
        [1., 3., 4.]])

In [ ]:
# log
torch.log(k)

tensor([[1.9459, 1.7918, 1.7918],
        [0.0000, 2.1972, 1.6094]])

In [ ]:
# exp
torch.exp(k)

tensor([[1.0966e+03, 4.0343e+02, 4.0343e+02],
        [2.7183e+00, 8.1031e+03, 1.4841e+02]])

In [ ]:
# sqrt
torch.sqrt(k)

tensor([[2.6458, 2.4495, 2.4495],
        [1.0000, 3.0000, 2.2361]])

In [ ]:
# sigmoid
torch.sigmoid(k)

tensor([[0.9991, 0.9975, 0.9975],
        [0.7311, 0.9999, 0.9933]])

In [ ]:
# softmax
torch.softmax(k,dim=0)

tensor([[0.5000, 0.9820, 0.2689],
        [0.5000, 0.0180, 0.7311]])

In [ ]:
# relu
torch.relu(k)

tensor([[1., 7., 3.],
        [1., 3., 4.]])

Inplace Operations

In [ ]:
m= torch.rand(2,3)
n= torch.rand(2,3)
print(m)
print(n)

tensor([[0.1573, 0.9624, 0.8598],
        [0.4523, 0.2741, 0.2890]])
tensor([[0.9360, 0.7612, 0.2429],
        [0.5200, 0.6026, 0.6322]])


In [ ]:
m+n

tensor([[1.0933, 1.7236, 1.1027],
        [0.9722, 0.8767, 0.9212]])

In [ ]:
# Inplace operations done, operations done, input of "m" are replace with  result
# m ki inputs value ko output se replace kr diya
# inplace(_) is done by  adding underscore(_)  in suffix of function operation
m.add_(n)

tensor([[1.0933, 1.7236, 1.1027],
        [0.9722, 0.8767, 0.9212]])

In [ ]:
m

tensor([[1.0933, 1.7236, 1.1027],
        [0.9722, 0.8767, 0.9212]])

In [ ]:
n.relu_()

tensor([[0.9360, 0.7612, 0.2429],
        [0.5200, 0.6026, 0.6322]])

Copying a Tensor

In [ ]:
a= torch.rand(2,3)
a

tensor([[0.2576, 0.2644, 0.6970],
        [0.0773, 0.0244, 0.9277]])

In [ ]:
# shallow copy
b=a

In [ ]:
b

tensor([[0.2576, 0.2644, 0.6970],
        [0.0773, 0.0244, 0.9277]])

In [ ]:
a[0][0]=0

In [ ]:
a

tensor([[0.0000, 0.2644, 0.6970],
        [0.0773, 0.0244, 0.9277]])

In [ ]:
b

tensor([[0.0000, 0.2644, 0.6970],
        [0.0773, 0.0244, 0.9277]])

In [ ]:
# Deep copy by using "Clone"
d=a.clone()
d


tensor([[0.0000, 0.2644, 0.6970],
        [0.0773, 0.0244, 0.9277]])

In [ ]:
a[0][0]=1

In [ ]:
a

tensor([[1.0000, 0.2644, 0.6970],
        [0.0773, 0.0244, 0.9277]])

In [ ]:
d

tensor([[0.0000, 0.2644, 0.6970],
        [0.0773, 0.0244, 0.9277]])

Tensor Operations on GPU

In [ ]:
torch.cuda.is_available()

True

In [ ]:
device= torch.device('cuda')

In [ ]:
# Creating a new tensor on GPU
torch.rand((2,3),device=device)


tensor([[0.4254, 0.8305, 0.3370],
        [0.6842, 0.5668, 0.6650]], device='cuda:0')

In [ ]:
# moving an existing tensor to GPU by using "to"
a= torch.rand(2,3)
a

tensor([[0.6795, 0.7765, 0.7181],
        [0.3093, 0.1860, 0.1592]])

In [ ]:
b= a.to(device)

Reshaping Tensors

In [ ]:
a= torch.ones(4,4)
a

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
# reshape
a.reshape(2,2,2,2)

tensor([[[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]],


        [[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]]])

In [ ]:
a.shape

torch.Size([4, 4])

In [ ]:
# Flattern
a.flatten()

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
b= torch.rand(2,3,4)
b

tensor([[[0.4684, 0.6240, 0.0316, 0.1161],
         [0.7814, 0.5641, 0.8298, 0.9454],
         [0.8039, 0.3937, 0.2775, 0.6415]],

        [[0.9067, 0.0206, 0.6342, 0.1146],
         [0.1025, 0.6809, 0.7543, 0.6712],
         [0.6454, 0.3490, 0.5121, 0.0585]]])

In [ ]:
b.shape

torch.Size([2, 3, 4])

In [ ]:
# Permute
c=b.permute(2,1,0)
c

tensor([[[0.4684, 0.9067],
         [0.7814, 0.1025],
         [0.8039, 0.6454]],

        [[0.6240, 0.0206],
         [0.5641, 0.6809],
         [0.3937, 0.3490]],

        [[0.0316, 0.6342],
         [0.8298, 0.7543],
         [0.2775, 0.5121]],

        [[0.1161, 0.1146],
         [0.9454, 0.6712],
         [0.6415, 0.0585]]])

In [ ]:
c.shape

torch.Size([4, 3, 2])

In [ ]:
# Unsqueeze: it is used to add dimensions on matrix at specify positon
c= torch.rand(226,226,3)
c.unsqueeze(0).shape

torch.Size([1, 226, 226, 3])

In [ ]:
# squeese: it is used to remove dimensions on specify position
d= torch.rand(1,20)
d.squeeze(0).shape


torch.Size([20])

Convert PyTorch to NumPy

: tensor to array

: array to tensor

To Tensor to numpy by using ".numpy()"

In [ ]:
import numpy as np

In [ ]:
a= torch.tensor([1,2,3])
a

tensor([1, 2, 3])

In [ ]:
b= a.numpy()

In [ ]:
b

array([1, 2, 3])

In [ ]:
type(b)

numpy.ndarray

To Convert NumPy to Tensor

 by using "torch.from_numpy()

In [ ]:
c=np.array([1,2,3])
c

array([1, 2, 3])

In [ ]:
type(c)

numpy.ndarray

In [ ]:
d=torch.from_numpy(c)
d

tensor([1, 2, 3])

In [ ]:
type(d)

NameError: name 'd' is not defined